
package org.ccnt.jax.web.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloDemo", targetNamespace = "http://service.ouc.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloDemo {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "testService", targetNamespace = "http://service.ouc.com/", className = "org.ccnt.jax.web.client.TestService")
    @ResponseWrapper(localName = "testServiceResponse", targetNamespace = "http://service.ouc.com/", className = "org.ccnt.jax.web.client.TestServiceResponse")
    public String testService(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
