
package org.ccnt.jax.web.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Service", targetNamespace = "http://serviceMapper.ouc.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Service {


    /**
     * 
     * @param arg0
     * @return
     *     returns org.ccnt.jax.web.client.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "testSelectUserById", targetNamespace = "http://serviceMapper.ouc.com/", className = "org.ccnt.jax.web.client.TestSelectUserById")
    @ResponseWrapper(localName = "testSelectUserByIdResponse", targetNamespace = "http://serviceMapper.ouc.com/", className = "org.ccnt.jax.web.client.TestSelectUserByIdResponse")
    public User testSelectUserById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
